name: secret_workflow_repository

on:
  workflow_dispatch:
    inputs:
      target_environment:
        description: 'Environment to run tests against'
        type: choice
        options:
          - staging
          - qa
        required: true
        default: 'staging'

jobs:
  job1:
    runs-on: ubuntu-latest
    environment: production_secret
    steps:
      - name: Step with a secret
        run: |
          echo "Hello World"
          echo "This is a secret value: ${{ secrets.SECRET_VAL }}"
